services:
    app.redsys_payment:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            - Eclyptox\SyliusRedsysPlugin\Payum\RedsysGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: "redsys_payment" }

    app.redsys_config:
        class: Eclyptox\SyliusRedsysPlugin\Form\Type\SyliusGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: "redsys_payment", label: "Redsys Payment" }
            - { name: form.type }
